#!/usr/bin/env python3
"""
fo-uploader — Upload fo-harvester artifacts to S3-compatible evidence storage.

Generated by ForensicsOperator — constants below are pre-filled with your config.
WARNING: This script contains your S3 credentials. Do not share or commit it.

Requirements: pip install boto3

Usage:
    python fo-uploader.py                      # auto-detect ./output/fo-artifacts-*.zip
    python fo-uploader.py --file evidence.zip  # upload a specific file
    python fo-uploader.py --dir ./output       # scan a directory
    python fo-uploader.py --prefix 2024-IR01   # store under a sub-folder in the bucket
"""
from __future__ import annotations

# ── Injected configuration — DO NOT EDIT ─────────────────────────────────────
ENDPOINT   = ""
ACCESS_KEY = ""
SECRET_KEY = ""
BUCKET     = ""
REGION     = ""
USE_SSL    = "true"
# ─────────────────────────────────────────────────────────────────────────────

import argparse
import glob
import sys
from pathlib import Path


def _build_client():
    try:
        import boto3
    except ImportError:
        print("ERROR: boto3 not installed. Run:  pip install boto3", file=sys.stderr)
        sys.exit(1)

    use_ssl = USE_SSL.lower() in ("true", "1", "yes")
    scheme  = "https" if use_ssl else "http"

    ep = ENDPOINT
    for prefix in ("https://", "http://"):
        if ep.lower().startswith(prefix):
            ep = ep[len(prefix):]
            break
    endpoint_url = f"{scheme}://{ep}" if ep else None

    return boto3.client(
        "s3",
        endpoint_url=endpoint_url,
        aws_access_key_id=ACCESS_KEY,
        aws_secret_access_key=SECRET_KEY,
        region_name=REGION or None,
    )


class _Progress:
    """Simple console progress bar for boto3 upload callbacks."""

    def __init__(self, total: int) -> None:
        self._total = total
        self._seen  = 0

    def __call__(self, chunk: int) -> None:
        self._seen += chunk
        pct = int(self._seen * 100 / self._total) if self._total else 100
        bar = "#" * (pct // 2) + "-" * (50 - pct // 2)
        print(f"\r  [{bar}] {pct:3d}%", end="", flush=True)


def _find_artifacts(search_dir: Path) -> list[Path]:
    pattern = str(search_dir / "fo-artifacts-*.zip")
    matches = sorted(glob.glob(pattern))
    if not matches:
        matches = sorted(glob.glob(str(search_dir / "*.zip")))
    return [Path(m) for m in matches]


def _upload(file_path: Path, bucket: str, key: str, s3) -> None:
    size_mb = file_path.stat().st_size / 1024 / 1024
    print(f"\nUploading {file_path.name} ({size_mb:.1f} MB)")
    print(f"  → s3://{bucket}/{key}")
    with open(file_path, "rb") as fh:
        s3.upload_fileobj(
            fh, bucket, key,
            Callback=_Progress(int(size_mb * 1024 * 1024)),
        )
    print(f"\n  Done.")


def main() -> None:
    if not ENDPOINT or not ACCESS_KEY or not SECRET_KEY or not BUCKET:
        print(
            "ERROR: Script is not configured. "
            "Download a fresh copy from ForensicsOperator → Collector.",
            file=sys.stderr,
        )
        sys.exit(1)

    parser = argparse.ArgumentParser(
        description="Upload fo-harvester artifacts to S3-compatible evidence storage."
    )
    parser.add_argument("--file",   metavar="PATH",   help="Upload a specific file")
    parser.add_argument("--dir",    metavar="DIR",    default="./output",
                        help="Directory to scan for fo-artifacts-*.zip (default: ./output)")
    parser.add_argument("--prefix", metavar="PREFIX", default="",
                        help="S3 key prefix (sub-folder inside the bucket)")
    args = parser.parse_args()

    if args.file:
        files = [Path(args.file)]
    else:
        files = _find_artifacts(Path(args.dir))
        if not files:
            print(f"No fo-artifacts-*.zip found in {args.dir}/", file=sys.stderr)
            print("Run fo-harvester.py first, or use --file to specify a path.", file=sys.stderr)
            sys.exit(1)

    s3 = _build_client()
    prefix = args.prefix.strip("/")

    for file_path in files:
        if not file_path.exists():
            print(f"ERROR: File not found: {file_path}", file=sys.stderr)
            continue
        key = f"{prefix}/{file_path.name}" if prefix else file_path.name
        _upload(file_path, BUCKET, key, s3)

    print("\nAll files uploaded. Go to ForensicsOperator → S3 Triage browser to import into a case.")


if __name__ == "__main__":
    main()
